### ISSUE TITLE
The palace_window_top_flat and the wrought_lattice_top are not craftable

### ISSUE THREAD

**Issue by Bastrabun** [runsy/jonez#2]
Looks like the xpanes:jonez:palace_window_top_flat cannot be crafted. When I try to use its recipe, I only get the xpanes:jonez:palace_window_bottom_flat as a result.

Same applies to the wrought lattice, only that I can craft nothing but the top.

Repro: 

Try to craft the following items.

jonez:wrought_lattice_top
xpanes:jonez:wrought_lattice_bottom
xpanes:jonez:palace_window_top_flat
xpanes:jonez:palace_window_bottom_flat

Also not sure about the double : in those names, is it supposed to be like that? The wrought lattice top seems to lack the double : ?

**Comment by runsy** [comment]
Check the last version.

**Comment by Bastrabun** [comment]
Forgot to push? :P

**Comment by runsy** [comment]
> Forgot to push? :P

Oops Hahaha Reuploaded.

**Comment by Bastrabun** [comment]
Strange, I made the update, but said items are still not craftable. Can you take a look again and specifically try to craft 

jonez:wrought_lattice_bottom
jonez:palace_window_top_flat

Those item that I handed out now are Unknown nodes, I guess that's a byproduct of the name change :P

**Comment by runsy** [comment]
I am in my holiday time. When I come back home I will fix :-)

**Comment by Bastrabun** [comment]
Can you look at the error again? It seems not to be solved even on latest version

**Comment by runsy** [comment]
Yes, I take care of that.

**Comment by runsy** [comment]
I uploaded my local working version. I think now it is finally solved.

**Comment by Bastrabun** [comment]
I pulled the latest, and I still can't craft them :D

**Comment by mk-pmb** [comment]
> I uploaded my local working version. I think now it is finally solved.

Would you mind sharing that version with us?
