### ISSUE TITLE
jonez:diamond_pavement is not craftable

### ISSUE THREAD

**Issue by Bastrabun** [runsy/jonez#4]
It's used in the recipe for the versailles tiles.

For my reference #359

**Comment by fluxionary** [comment]
The issue isn't that no crafting recipe is defined:
https://github.com/runsy/jonez/blob/343e9d657dd6669a3e20cec72f7feeb3ffdff6e4/init.lua#L328-L334

The issue is that it's using the wrong name for the nodes w.r.t. moreblocks.

**Comment by runsy** [comment]
OK I will solve as soon as possible.

**Comment by runsy** [comment]
Finally I've found the error that not allowed some items crafted.

Solved.
